# Generated by Django 6.0.4 on 2026-05-14 02:09

from django.db import migrations

def populate_status(apps, schema_editor):
    entries = {
        "published": "A post available for all to view",
        "draft": "A post only visible to author", 
        "archived": "An older post visible to only the logged user"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
